### ISSUE TITLE
Inline code listing wraps around a code listing in a figure

### ISSUE THREAD

**Issue by chrisseaton** [simonmar/par-tutorial#2]
With reference to version 1.1, in the generated PDF page 22 ends with an inline listing that continues over the page. However, page 23 is an unrelated full page listing, and the listing from page 22 only continues on page 24. It's clear if you look at the bottom of page 23 where there's a figure title, but if you're reading it through it's very easy to turn from page 22 to 23 and be confused about the listing. The inline listing is basically wrapping around the figure listing.

Perhaps you could make the inline listing which wraps over the page boundary into its own figure as well? Then LaTeX would stop it wrapping around the other figure.

**Comment by chrisseaton** [comment]
Sorry, submitted a possible fix for this but it created a new issue #3, so the pull request to put this into its own figure is there.

**Comment by simonmar** [comment]
pull request merged, thanks!  Closing this issue.
